widget:
  bot_username: "bot_name" # str required
  button_style: "large"  # "large", "medium", or "small"
  userpic: true # Set to False if you do not want to display the user's photo
  corner_radius: null # or int for custom corner radius
  request_access: true # Set to send messages from your bot
cookie:
  expiry_days: 30
secret_key: "Your secret key" # secret for jwt encode/decode
